language: python

python:
 - 2.7

services:
 - redis-server

before_script:
 - mysql -e 'create database valentine;'
 - mysql -D valentine < vilya/databases/schema.sql

install:
 - pip install -r requirements.txt

script:
 - py.test tests
